# Generated by Django 6.0.2 on 2026-05-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0002_grievance_assigned_message_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='grievance_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
