# Generated by Django 6.0.2 on 2026-05-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0004_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_function',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
