# Generated by Django 6.0.2 on 2026-05-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0005_user_staff_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='resolution_image',
            field=models.ImageField(blank=True, null=True, upload_to='resolution_proofs/'),
        ),
    ]
