# Generated by Django 6.0.2 on 2026-05-18 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0006_grievance_resolution_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('meeting_type', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], max_length=10)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('meeting_location', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
